@startuml check-in
start
:Выбор студента/
:Выбор комнаты/
if (Студент существует?) then (Да)
  if (Студент уже заселен?) then (Да)
    :Сообщить об ошибке/
  else (Нет)
    if (Есть свободное место?) then (Да)
      :Заселить студента;
      :Сохранить изменения;
    else (Нет)
      :Сообщить об ошибке/
    endif
  endif
else (Нет)
  :Сообщить об ошибке/
endif
stop
@enduml