@startuml check-out
start
:Выбрать студента/
if (Студент найден?) then (Да)
  :Выселить студента;
  :Освободить место в комнате;
  :Сохранить изменения;
else (Нет)
  :Сообщить об ошибке/
endif
stop
@enduml