@startuml free-place
start
:Выбрать комнату/
:Получить информацию о занятости комнаты/
if (Есть свободные места?) then (Да)
  :Показать количество свободных мест/
else (Нет)
  :Вывести: "Мест нет"/
endif
stop
@enduml